# Project-wide Gradle settings.

# JVM arguments for the Gradle daemon.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# AndroidX.
android.useAndroidX=true

# Kotlin code style.
kotlin.code.style=official

# Smaller R classes for faster builds.
android.nonTransitiveRClass=true

# Enable the configuration cache.
org.gradle.configuration-cache=true
